#!/bin/bash
set -ex

[[ $UID != 0 ]] && exec sudo -E "$(readlink -f "$0")" "$@"

up() {
    killall wpa_supplicant dhcpcd || true
    ip netns add physical
    ip -n physical link add wg0 type wireguard
    ip -n physical link set wg0 netns 1
    wg setconf wg0 /etc/wireguard/wg0.conf
    ip addr add 192.168.43.0/24 dev wgvpn0
    ip link set wlp2s0 down
    ip link set wlp2s0 netns physical
    iw phy phy0 set netns name physical
    ip netns exec physical dhcpcd -b wlp2s0
    ip netns exec physical wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-wlan0.conf -iwlan0
    ip link set wg0 up
    ip route add default dev wgvpn0
}

down() {
    killall wpa_supplicant dhcpcd || true
    ip -n physical link set wlp2s0 down
    ip -n physical link set wlp2s0 netns 1
    ip netns exec physical iw phy phy0 set netns 1
    ip link del wg0
    ip netns del physical
    dhcpcd -b wlp2s0
    wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-wlan0.conf -iwlan0
}

execi() {
    exec ip netns exec physical sudo -E -u \#${SUDO_UID:-$(id -u)} -g \#${SUDO_GID:-$(id -g)} -- "$@"
}

command="$1"
shift

case "$command" in
    up) up "$@" ;;
    down) down "$@" ;;
    exec) execi "$@" ;;
    *) echo "Usage: $0 up|down|exec" >&2; exit 1 ;;
esac
