#!/bin/bash

## Created By Aditya Shakya

#MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -xoffset 0 -yoffset 30 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 5 <<< " Logout| Suspend| Hibernate| Reboot| Poweroff")"
case "$MENU" in
  *Logout) i3-msg exit ;;
  *Suspend) systemctl suspend ;;
  *Hibernate) systemctl hibernate ;;
  *Reboot) systemctl reboot ;;
  *Shutdown) systemctl poweroff
esac
